# kafka-ui-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: production
spec:
  type: ClusterIP # Use NodePort if LoadBalancer is not supported
  selector:
    app: kafka-ui
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
