services:
  auth-service:
    build:
      context: ./Services/Auth_Service
      dockerfile: Dockerfile

    image: auth-servicee:latest
    ports:
      - "3001:3001"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: 1234
      DB_NAME: authDB
      DB_DIALECT: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: authDB
    ports:
      - "4444:5432"
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql

  gateway-service:
    build:
      context: ./Services/GateWayService
      dockerfile: Dockerfile

    image: gateway-service:latest
    ports:
      - "3000:3000"
    environment:
      AUTH_BASE_URL: http://auth-service:3001
      JWT_SECRET: ManurChop
      AUTH_SERVICE_NAME: authService
    depends_on:
      - postgres
