apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-data-0
  namespace: production
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: zookeeper-storage
  hostPath:
    path: "/mnt/data/kafka-0"
