# zookeeper-persistent-volume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: zookeeper-local-storage
  hostPath:
    path: /data/zookeeper/zookeeper-0

---
# zookeeper-persistent-volume-claim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pvc
  namespace: production
spec:
  storageClassName: zookeeper-local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
