# zookeeper-persistent-volume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv
  namespace: production
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/zookeeper

---
# zookeeper-persistent-volume-claim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
