apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-zookeeper-data-0
  namespace: production
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: zookeeper-storage
  hostPath:
    path: "/mnt/data/zookeeper-0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-zookeeper-log-0
  namespace: production
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: zookeeper-storage
  hostPath:
    path: "/mnt/data/zookeeper-logs-0"
