apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
  namespace: production
  labels:
    app: zookeeper
spec:
  clusterIP: None # Headless service for stateful pods
  selector:
    app: zookeeper
  ports:
    - name: client
      port: 2181
    - name: follower
      port: 2888
    - name: election
      port: 3888
