apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:latest
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092 # No tcp://
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092 # Correct format without tcp://
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT
            - name: KAFKA_LISTENER_NAME_PLAINTEXT
              value: PLAINTEXT
            - name: KAFKA_LISTENER_PORT_PLAINTEXT
              value: "9092"
            - name: KAFKA_LISTENER_INTER_BROKER_SECURITY_PROTOCOL
              value: PLAINTEXT
            - name: KAFKA_BROKER_ID
              value: "1"
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
